const $ = (id) => document.getElementById(id);
let currentMeeting = null;
const api = async (url, options = {}) => { const response = await fetch(url, options); const text = await response.text(); let body = {}; try { body = text ? JSON.parse(text) : {}; } catch (_) {} if (!response.ok) throw new Error(body.error || `请求失败 (${response.status})`); return body; };
const toast = (message, error = false) => { const node = $('toast'); node.textContent = message; node.style.background = error ? '#9b4242' : '#13222d'; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); };
const requireMeeting = () => { const id = $('meetingId').value.trim(); if (!id) { toast('请先创建或加载会议', true); return null; } return id; };
async function refreshHealth() { try { const data = await api('/health'); $('health').innerHTML = `<span class="dot"></span><span>服务正常 · ${data.jobs.pending} 个待处理任务</span>`; } catch (_) { $('health').innerHTML = '<span class="dot" style="background:#c25353"></span><span>服务不可用</span>'; } }
async function loadMeeting() { const id = requireMeeting(); if (!id) return; try { const meeting = await api(`/api/v1/meetings/${id}`); currentMeeting = meeting; $('meetingStatus').textContent = meeting.status === 'ended' ? '已结束' : '进行中'; await Promise.all([loadSpeakers(), refreshData(), loadJobs()]); } catch (error) { toast(error.message, true); } }
async function loadSpeakers() { const id = requireMeeting(); if (!id) return; const speakers = await api(`/api/v1/meetings/${id}/speakers`); $('speakers').className = `list${speakers.length ? '' : ' empty'}`; $('speakers').innerHTML = speakers.length ? speakers.map(s => `<div><span>${escapeHtml(s.name)}</span><code>${s.id.slice(0,8)}</code></div>`).join('') : '还没有说话人'; $('speakerId').innerHTML = '<option value="">未知说话人</option>' + speakers.map(s => `<option value="${s.id}">${escapeHtml(s.name)}</option>`).join(''); }
async function refreshData() { const id = requireMeeting(); if (!id) return; const [summaries, board] = await Promise.all([api(`/api/v1/meetings/${id}/summaries`), api(`/api/v1/meetings/${id}/board`)]); renderSummaries(summaries); renderBoard(board); }
async function loadJobs() { const id = requireMeeting(); if (!id) return; const jobs = await api(`/api/v1/jobs?meeting_id=${encodeURIComponent(id)}`); const node = $('jobs'); node.className = `jobs-table${jobs.length ? '' : ' empty'}`; node.innerHTML = jobs.length ? `<table><thead><tr><th>类型</th><th>状态</th><th>重试</th><th>时间</th></tr></thead><tbody>${jobs.map(j => `<tr><td>${j.job_type}</td><td><span class="pill ${j.status === 'failed' ? 'failed' : ''}">${j.status}</span></td><td>${j.retry_count}</td><td>${j.available_at}</td></tr>`).join('')}</tbody></table>` : '暂无任务'; }
function renderSummaries(items) { const node = $('summaries'); node.className = `feed${items.length ? '' : ' empty'}`; node.innerHTML = items.length ? items.slice().reverse().map(item => `<article class="summary"><strong>${formatMs(item.window_start_ms)} — ${formatMs(item.window_end_ms)}</strong><span>${escapeHtml(item.content.summary || item.content.key_points?.join('；') || '暂无内容')}</span></article>`).join('') : '暂无 Summary'; }
function renderBoard(data) { $('boardVersion').textContent = `v${data.version || 0}`; const board = data.content || {}; const groups = [['topics','主题'],['decisions','决策'],['key_points','关键点'],['open_questions','待确认问题'],['risks','风险']]; const parts = groups.filter(([key]) => (board[key] || []).length).map(([key, title]) => `<div class="board-group"><h3>${title}</h3><ul>${board[key].map(v => `<li>${escapeHtml(v)}</li>`).join('')}</ul></div>`); if ((board.action_items || []).length) parts.push(`<div class="board-group"><h3>行动项</h3>${board.action_items.map(v => `<div class="action">${escapeHtml(v.content)}<small>${escapeHtml(v.owner || '未指派')} · ${escapeHtml(v.status || 'open')}</small></div>`).join('')}</div>`); $('board').className = `board${parts.length ? '' : ' empty'}`; $('board').innerHTML = parts.join('') || '暂无 Board 内容'; }
function formatMs(ms) { const total = Math.floor(ms / 1000); return `${String(Math.floor(total / 60)).padStart(2,'0')}:${String(total % 60).padStart(2,'0')}`; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
$('meetingForm').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await api('/api/v1/meetings', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({title:$('title').value}) }); $('meetingId').value = result.id; toast('会议已创建'); await loadMeeting(); } catch (error) { toast(error.message, true); } });
$('loadMeeting').addEventListener('click', loadMeeting); $('refresh').addEventListener('click', () => loadMeeting());
$('speakerForm').addEventListener('submit', async (event) => { event.preventDefault(); const id = requireMeeting(); if (!id) return; try { await api(`/api/v1/meetings/${id}/speakers`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({name:$('speakerName').value}) }); $('speakerName').value = ''; toast('说话人已添加'); await loadSpeakers(); } catch (error) { toast(error.message, true); } });
$('endMeeting').addEventListener('click', async () => { const id = requireMeeting(); if (!id) return; try { await api(`/api/v1/meetings/${id}/end`, {method:'POST'}); toast('会议已结束'); await loadMeeting(); } catch (error) { toast(error.message, true); } });
$('segmentForm').addEventListener('submit', async (event) => { event.preventDefault(); const id = requireMeeting(); if (!id) return; const file = $('audio').files[0]; if (!file) return toast('请选择音频文件', true); const form = new FormData(); [['speaker_id','speakerId'],['sequence_no','sequence'],['start_ms','startMs'],['end_ms','endMs'],['transcript','transcript']].forEach(([key, input]) => { if ($(input).value) form.append(key, $(input).value); }); form.append('audio', file); $('uploadStatus').textContent = '上传中...'; try { await api(`/api/v1/meetings/${id}/segments`, {method:'POST', body:form}); toast('音频分段已上传'); $('uploadStatus').textContent = '已加入处理队列'; $('sequence').value = Number($('sequence').value) + 1; await loadJobs(); } catch (error) { $('uploadStatus').textContent = '上传失败'; toast(error.message, true); } });
refreshHealth(); setInterval(refreshHealth, 15000);
